version: '3.8'

services:
  MyBlog_CategoryDb:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - category_data:/data/db

  MyBlog_ReactionDb:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - reaction_data:/data/db

  MyBlog_CommentDb:
    image: couchbase:community
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
      - "8095-8097"
      - "11207"
      - "11280"
    volumes:
      - comment_data:/var/lib/couchbase/data

  MyBlog_ContentDb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - content_data:/data/db

  MyBlog_IdentityDb:
    image: mongo:latest
    ports:
      - "27021:27017"
    volumes:
      - identity_data:/data/db
  
  MyBlog_Rabbitmq:
    image: rabbitmq:3.11.16-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  MyBlog_Datalust_Seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - datalust_seq_data:/data
  Myblog_RedisDb:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  MyBlog_Minio: 
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Strong#Pass#2023
    command: server --console-address ":9001" /data
  MyBlog_Elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    expose:
      - 9200
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=DkIedPPSCb
    networks:
      - es-net
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  MyBlog_Kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    environment:
      - ELASTICSEARCH_HOSTS=http://myblog_elasticsearch:9200
    expose:
      - 5601
    networks:
      - es-net
    depends_on:
      - MyBlog_Elasticsearch
    ports:
      - 5601:5601
    volumes:
      - kibana-data:/usr/share/kibana/data
networks:
  rabbitmq:
    driver: bridge
  es-net:
    driver: bridge

volumes:
  category_data:
  reaction_data:
  comment_data:
  content_data:
  identity_data:
  rabbitmq_data:
  datalust_seq_data:
  minio_data:
  redis_data:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local 